
package principalpackage;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.ComponentOrientation;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Image;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.border.Border;
import javax.swing.border.CompoundBorder;
import javax.swing.border.EmptyBorder;

public class InicioPanel extends javax.swing.JPanel {

    /**
     * Creates new form InicioPanel
     */
    public InicioPanel() {
        initComponents();
        txtinfoEmpresa.setLineWrap(true); // Ajustar las líneas al ancho del JTextArea
        txtinfoEmpresa.setWrapStyleWord(true); // Ajuste de líneas por palabras completas
        
        
        // Configurar el JTextArea para que no tenga fondo ni borde visibles
        txtinfoEmpresa.setOpaque(false); // Hace que el fondo sea transparente
        txtinfoEmpresa.setBorder(null);  // Elimina el borde
        
        // Establecer el layout del panel como GridBagLayout para centrar la imagen
       txtinfoEmpresa.setComponentOrientation(ComponentOrientation.LEFT_TO_RIGHT);
       txtinfoEmpresa.setAlignmentX(txtinfoEmpresa.CENTER_ALIGNMENT);
       txtinfoEmpresa.setBorder(new EmptyBorder(50, 50, 0, 50));
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtinfoEmpresa = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(null);

        txtinfoEmpresa.setEditable(false);
        txtinfoEmpresa.setBackground(java.awt.Color.lightGray);
        txtinfoEmpresa.setColumns(20);
        txtinfoEmpresa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtinfoEmpresa.setRows(5);
        txtinfoEmpresa.setText("SISTEMA DE PLANILLA \n\nTALLER DE MOTOS SUAREZ S.A de C.V.\n\nMisión: Ofrecer nuestros productos, servicios de reparación y mantenimiento de motocicletas con alta calidad y eficiencia, brindando un servicio confiable y profesional que garantice la satisfacción total de nuestros clientes. \n\nVisión: Convertirnos en la empresa líder en la venta de productos, servicios de reparación y mantenimiento de motocicletas en San Salvador, reconocidos por la excelencia en el servicio y la innovación en nuestro rubro. ");
        txtinfoEmpresa.setAutoscrolls(false);
        txtinfoEmpresa.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtinfoEmpresa.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtinfoEmpresa.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtinfoEmpresa.setEnabled(false);
        txtinfoEmpresa.setFocusable(false);
        txtinfoEmpresa.setOpaque(false);
        txtinfoEmpresa.setRequestFocusEnabled(false);
        txtinfoEmpresa.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setViewportView(txtinfoEmpresa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleParent(this);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtinfoEmpresa;
    // End of variables declaration//GEN-END:variables
}
